<?php

$checkId = $this->getCheck()->getCheckId();

?>
<div class="<?php echo $this->getCheck()->getContentType() ?> healthcheck-box">
    <h2><?php echo $this->getCheck()->getTitle(); ?></h2>

    <div id="<?php echo $checkId; ?>"></div>

    <?php  if($this->getCheck()->getType() == Hackathon_HealthCheck_Helper_Data::TYPE_ONDEMAND): ?>
        <a href="#" class="execute-button" onclick="Hackathon_HealthCheck.showData('<?php echo $checkId; ?>');"><?php echo $this->__('Execute Check') ?></a>
    <?php else: ?>
        <script>
            jQuery(document).ready(function() {
                Hackathon_HealthCheck.showData('<?php echo $checkId; ?>');
                jQuery('.execute-button').click(function() {
                    jQuery(this).fadeOut();
                })
            });
        </script>

    <?php endif; ?>

</div>