<?php

$checkId = $this->getCheck()->getCheckId();

?>
<div id="<?php echo $checkId; ?>" class="<?php echo $this->getCheck()->getContentType() ?> healthcheck-box">
    <h2><?php echo $this->getCheck()->getTitle(); ?></h2>

    <?php  if($this->getCheck()->getType() == Hackathon_HealthCheck_Helper_Data::TYPE_ONDEMAND): ?>
        <a href="#" onclick="alert('ondemand')">Get it!</a>
    <?php else: ?>
        <script>
            jQuery(document).ready(function() {
                Hackathon_HealthCheck.showData('<?php echo $checkId; ?>');
            });
        </script>

    <?php endif; ?>
</div>

